# Generated by Django 4.2.4 on 2023-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bandits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucb1model',
            name='min_views',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ucb1model',
            name='significance_level',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='ucb1model',
            name='winning_arm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
