# Generated by Django 4.2.4 on 2023-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bandits', '0002_ucb1model_min_views_ucb1model_significance_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epsilondecaymodel',
            name='min_views',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='epsilondecaymodel',
            name='significance_level',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='epsilondecaymodel',
            name='winning_arm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epsilongreedymodel',
            name='min_views',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='epsilongreedymodel',
            name='significance_level',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='epsilongreedymodel',
            name='winning_arm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
