# Generated by Django 4.2.4 on 2023-08-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bandits', '0003_epsilondecaymodel_min_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epsilondecaymodel',
            name='beta',
        ),
    ]
