# Generated by Django 4.1.10 on 2023-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_bandits", "0001_squashed_0004_remove_epsilondecaymodel_beta"),
    ]

    operations = [
        migrations.AddField(
            model_name="banditflag",
            name="ignore_for_authenticated_users",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the flag will not be active for authenticated users and no stats will be recorded.",
            ),
        ),
    ]
